# Generated by Django 5.2 on 2025-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_amount_transaction_vgt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MINT', 'Mint'), ('BUY', 'Buy'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received'), ('GIFT_SEND_BACK', 'Gift Send Back'), ('REDEEM', 'Redeem'), ('VAULT_DEPOSIT', 'Vault Deposit'), ('VAULT_WITHDRAWAL', 'Vault Withdrawal')], max_length=50),
        ),
    ]
