# Generated by Django 5.2 on 2025-05-02 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UAE', 'UAE'), ('CAD', 'CAD')], max_length=3, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GoldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('gold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('MINT', 'Mint'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received'), ('GIFT_SEND_BACK', 'Gift Send Back'), ('REDEEM', 'Redeem'), ('VAULT_DEPOSIT', 'Vault Deposit'), ('VAULT_WITHDRAWAL', 'Vault Withdrawal')], default='MINT', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fiat_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stop_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Stop limit as a percentage (e.g., 50.00 for 50%)', max_digits=5),
        ),
    ]
