# Generated by Django 5.2 on 2025-05-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_golddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text="The user's preferred currency.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAE', 'UAE'), ('CAD', 'CAD')], default='USD', max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_currency', models.OneToOneField(blank=True, help_text='The currency used throughout the application.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_setting', to='core.currency')),
            ],
        ),
    ]
