# Generated by Django 5.2 on 2025-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_currency_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UAE', 'UAE'), ('CAD', 'CAD')], help_text="The user's preferred currency.", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='selected_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAE', 'UAE'), ('CAD', 'CAD')], default='USD', help_text='The currency used throughout the application.', max_length=3),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stop_limit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('MINT', 'Mint'), ('REDEEM', 'Redemption'), ('BUY', 'Purchase Fiat'), ('SELL', 'Sell Fiat'), ('TRANSFER', 'Transfer Token'), ('VAULT_DEPOSIT', 'Vault Deposit'), ('VAULT_WITHDRAWAL', 'Vault Withdrawal')], default='MINT', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vgt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
