# Generated by Django 5.2 on 2025-04-12 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='vgt_amount',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='visci_balance',
            new_name='vgt_balance',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='gold_grams',
        ),
        migrations.AddField(
            model_name='vault',
            name='vgt_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MINT', 'Mint'), ('BUY', 'Buy'), ('GIFT_SENT', 'Gift Sent'), ('GIFT_RECEIVED', 'Gift Received'), ('REDEEM', 'Redeem'), ('VAULT_DEPOSIT', 'Vault Deposit'), ('VAULT_WITHDRAWAL', 'Vault Withdrawal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.vault'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vault',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_email', models.EmailField(max_length=254)),
                ('vgt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_claimed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pending_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
