# Generated by Django 5.2 on 2025-06-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
