# Generated by Django 4.2.24 on 2025-09-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rst_adv', models.DecimalField(blank=True, decimal_places=2, help_text='Advance payment made for RST booking', max_digits=10, null=True)),
                ('rst_due', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount for RST booking', max_digits=10, null=True)),
                ('rst_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('sold_by', models.CharField(max_length=100)),
                ('item_count', models.IntegerField(default=0, editable=False)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_sale_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('GOLD', 'Gold'), ('RST', 'RST Booking')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional details like card type or gold description', null=True)),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund')], default='PAYMENT', max_length=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting_ledger.sales')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('GOLD', 'Gold'), ('RST', 'RST Booking')], max_length=10)),
                ('code', models.IntegerField(blank=True, help_text='Item code within the sale, can be null for order items', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the item, can be null for order items', max_digits=10, null=True)),
                ('purity_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price on market rate at the time of business date', max_digits=10, null=True)),
                ('description', models.TextField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting_ledger.sales')),
            ],
        ),
        migrations.CreateModel(
            name='RSTVoided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voided_at', models.DateTimeField(auto_now_add=True)),
                ('rst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voided_info', to='accounting_ledger.rst')),
            ],
        ),
        migrations.CreateModel(
            name='RSTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Item code within the RST booking')),
                ('purity', models.CharField(max_length=50)),
                ('rst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rst_items', to='accounting_ledger.rst')),
            ],
        ),
        migrations.AddField(
            model_name='rst',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rst_details', to='accounting_ledger.sales'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Order number same as invoice number', max_length=50, unique=True)),
                ('assigned_to', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, help_text='Expected delivery date for the order', null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='accounting_ledger.sales')),
            ],
        ),
        migrations.CreateModel(
            name='GoldPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purity', models.CharField(max_length=50)),
                ('payment', models.OneToOneField(limit_choices_to={'method': 'GOLD'}, on_delete=django.db.models.deletion.CASCADE, related_name='gold', to='accounting_ledger.salepayment')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('REFUND_ORDER', 'Refund – Order'), ('REFUND_RST', 'Refund – RST'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('GOLD', 'Gold'), ('RST', 'RST Booking')], max_length=10)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_ledger.salepayment')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_ledger.sales')),
            ],
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('sale', 'code'), name='uniq_sale_code_when_present'),
        ),
        migrations.AddConstraint(
            model_name='rstitem',
            constraint=models.UniqueConstraint(fields=('rst', 'code'), name='uniq_rst_code'),
        ),
    ]
