# Generated by Django 4.2.24 on 2025-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='uniq_sale_code_when_present',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='code',
            field=models.IntegerField(blank=True, help_text='Item code within the sale, can be null for order items', null=True, unique=True),
        ),
    ]
