# Generated by Django 4.2.24 on 2025-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0002_remove_saleitem_uniq_sale_code_when_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
    ]
