# Generated by Django 4.2.24 on 2025-09-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0003_alter_sales_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('purity', models.CharField(max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight of the item, can be null if not measured yet', max_digits=10, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RST_BOOKED', 'RST Booked'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('VOIDED', 'Voided')], default='AVAILABLE', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rstitem',
            name='uniq_rst_code',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rstitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rstitem',
            name='purity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='method',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='purity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the order was completed', null=True),
        ),
        migrations.AddField(
            model_name='rst',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When RST was completed', null=True),
        ),
        migrations.AddField(
            model_name='rstitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The remaining amount due after this payment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='due_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('REFUND_ORDER', 'Refund – Order'), ('REFUND_RST', 'Refund – RST'), ('OTHER', 'Other')], default='OTHER', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('GOLD', 'Gold'), ('RST', 'RST Booking')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='kind',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('RST_ADVANCE', 'RST Advance Payment'), ('RST_BALANCE', 'RST Balance Payment')], default='PAYMENT', max_length=200),
        ),
        migrations.AddField(
            model_name='rstitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounting_ledger.item'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting_ledger.item'),
        ),
    ]
