# Generated by Django 4.2.24 on 2025-09-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0004_item_remove_rstitem_uniq_rst_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rstitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounting_ledger.item'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='accounting_ledger.item'),
        ),
    ]
