# Generated by Django 4.2.24 on 2025-10-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0005_alter_rstitem_item_alter_saleitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='purity_price',
            field=models.CharField(blank=True, help_text='Price on market rate at the time of business date', null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_sale_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
