# Generated by Django 4.2.24 on 2025-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0006_alter_saleitem_purity_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpayment',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
