# Generated by Django 4.2.24 on 2025-10-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0007_alter_goldpayment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rst',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked (Partial Payment)'), ('COMPLETED', 'Completed (Full Payment)'), ('VOIDED', 'Voided')], default='BOOKED', max_length=100),
        ),
    ]
