# Generated by Django 4.2.24 on 2025-11-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0008_order_item_description_rst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(default='store-exp', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('REFUND_ORDER', 'Refund – Order'), ('REFUND_RST', 'Refund – RST'), ('GOLD_CASHBACK', 'Gold Cashback'), ('OTHER', 'Other')], default='OTHER', max_length=200),
        ),
    ]
