# Generated by Django 4.2.24 on 2025-11-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0009_expense_expense_type_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pending_jewellery_weight', models.DecimalField(decimal_places=3, default=0, help_text='jewellery outstanding from artisan', max_digits=10)),
                ('cash_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_audit_date', models.DateField()),
                ('last_transaction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MeltingGoldBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_period', models.DurationField()),
                ('j_back_to_store', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_for_melting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_gold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cash_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_audit_date', models.DateField()),
                ('last_transaction_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SupplierOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Jewellery delivery date')),
                ('j_total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('j_total_value', models.CharField()),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'receive payment'), ('DELIVER', 'deliver jewellery')], max_length=20)),
                ('purchase_rate_per_bhori', models.CharField(blank=True, help_text='Set only when order_kind = RECEIVE', max_length=20, null=True)),
                ('batch_id', models.CharField()),
                ('note', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounting_ledger.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCashbook',
            fields=[
                ('cashbook_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashbook', to='accounting_ledger.supplier')),
                ('supplier_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbook_entries', to='accounting_ledger.supplierorders')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItemTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=100)),
                ('date_of_transfer', models.DateField()),
                ('type_of_transfer', models.CharField(choices=[('OUT', 'Out'), ('IN', 'In')], max_length=20)),
                ('foreign_store_itemcode', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_transfers', to='accounting_ledger.item')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryGold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gold_to_artisan_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_withdrawn_gold_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('owner_withdrawn_gold_value', models.IntegerField(blank=True, null=True)),
                ('exchange_to_store_gold', models.DecimalField(decimal_places=2, help_text='Exchanged the amount of gold to jewellery and back to store', max_digits=10)),
                ('note', models.TextField(blank=True, help_text='Mention pre/post recovery exchange.')),
                ('melting_gold_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_records', to='accounting_ledger.meltinggoldbook')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('RAW_G', 'receive raw gold'), ('DELIVER_J', 'deliver jewellery')], max_length=20)),
                ('purchase_rate_per_bhori', models.CharField(blank=True, help_text='Set only when order_kind = RECEIVE', max_length=20, null=True)),
                ('total_gold_value', models.CharField()),
                ('receive_source', models.CharField(blank=True, choices=[('TATI_BAZAR', 'artisan tati bazaar'), ('MELTING_GOLD', 'store melting gold'), ('BOUGHT_GOLD', 'store bought gold')], help_text='Set only when order_kind = RECEIVE', max_length=20, null=True)),
                ('item_category', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounting_ledger.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanCashbook',
            fields=[
                ('cashbook_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashbook', to='accounting_ledger.artisan')),
                ('artisan_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='accounting_ledger.artisanorders')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='karigar_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounting_ledger.artisanorders'),
        ),
        migrations.AddField(
            model_name='item',
            name='recovery_gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounting_ledger.recoverygold'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounting_ledger.supplierorders'),
        ),
    ]
