# Generated by Django 4.2.24 on 2025-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0010_artisan_meltinggoldbook_supplier_item_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
