# Generated by Django 4.2.26 on 2025-12-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0011_alter_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanorders',
            name='gold_from_melting_recovery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisan_orders', to='accounting_ledger.recoverygold'),
        ),
        migrations.AddField(
            model_name='artisanorders',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artisancashbook',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='item_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='receive_source',
            field=models.CharField(blank=True, choices=[('TATI_BAZAR', 'artisan tati bazaar'), ('MELTING_GOLD', 'store melting gold'), ('BOUGHT_GOLD', 'store bought gold')], help_text='Set only when transaction_type = RECEIVE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='total_gold_value',
            field=models.CharField(help_text='Total value of gold received, transaction_type = RECEIVE', null=True),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='transaction_type',
            field=models.CharField(choices=[('RAW_G', 'receive raw gold, order_kind=RECEIVE'), ('DELIVER_J', 'deliver jewellery, order_kind=PROVIDE')], max_length=20),
        ),
    ]
