# Generated by Django 4.2.26 on 2025-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0012_artisanorders_gold_from_melting_recovery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='pending_jewellery_weight',
        ),
        migrations.AddField(
            model_name='artisan',
            name='jewellery_balance_g',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Running gold balance in grams. Positive: artisan owes jewellery. Negative: we owe gold.', max_digits=10),
        ),
    ]
