# Generated by Django 4.2.26 on 2025-12-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ledger', '0013_remove_artisan_pending_jewellery_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisancashbook',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashbook', to='accounting_ledger.artisan'),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounting_ledger.artisan'),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='gold_from_melting_recovery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artisan_orders', to='accounting_ledger.recoverygold'),
        ),
        migrations.AlterField(
            model_name='artisanorders',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorders',
            name='purchase_rate_per_bhori',
            field=models.CharField(blank=True, help_text='Set only when transaction_type=DELIVER', max_length=20, null=True),
        ),
    ]
